name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Gradle Android
      uses: Raul6469/android-gradle-action@2.0.0
      with:
        # The ./gradlew command arguments
        script: 
        # Your Android license agreement id
        android-licence: # optional
